---
title: "Week10_fri_exercises"
author: "shuna"
date: "3/23/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, fig.align = "center")
```

```{r}
library(tidyverse)
library(ggraph)
library(igraph)
library(tidygraph)
library(ggforce)
library(concaveman)
```

```{r}
karate_edges <- read_table(
  "soc-karate.zip",
  col_names = FALSE,
  skip = 24
) |>
  print()

karate_nodes <- 1:34 |>
  as_tibble()
```

```{r}
karate_netw <- tbl_graph(
  edges = karate_edges,
  nodes = karate_nodes,
  directed = FALSE
)
```

```{r}
# number of nodes
gorder(karate_netw)
# number of edges
gsize(karate_netw)
```

```{r}
# simple graph has no parallel edges or loops
is_simple(karate_netw)
```

```{r}
karate_netw
```
```{r}
karate_netw <- karate_netw |>
  activate(nodes) |>
  mutate(
    role = case_when(
      value == 1 ~ "Instructor",
      value == 34 ~ "President",
      TRUE ~ "Other"
    )
  ) |>
  print()
```

```{r}
karate_degree <- karate_netw |>
  activate(nodes) |>
  mutate(degree = centrality_degree()) |>
  arrange(-degree) |>
  as_tibble() |>
  print()

karate_degree |>
  head(2)
```
```{r}
karate_netw |>
  convert(to_shortest_path, role == "Instructor", role == "President") |>
  as_tibble()
  
```
```{r}
all_shortest_paths(karate_netw, 1, 34)$res
```



```{r}
karate_netw |>
  activate(nodes) |>
  mutate(cluster_coef = local_transitivity()) |>
  filter(role == c("Instructor", "President")) |>
  as_tibble()
```
Instructor is in a tighter network, people around him are closer to him compared to people around the president. 

```{r}
largest.cliques(karate_netw)
```


```{r}
karate_netw|>
  activate(nodes) |>
  mutate(component_id = group_components()) |>
  as_tibble() |>
  group_by(component_id) |>
  group_split()|>
  map(pluck("role")) |>
  print()
```

```{r}
karate_netw <- karate_netw |>
  activate(nodes) |>
  mutate(community_id = group_louvain(),
         community_name = paste("Community", community_id)) |>
  print()
```
```{r}
node_positions
```
```{r}
karate_layout
```


```{r}
karate_layout <- create_layout(karate_netw, layout = "stress")
layout_attributes <- attributes(karate_layout)
node_positions <- read_csv("karate_node_positions.csv")
karate_layout <-
  karate_layout |>
  select(-x, -y) |>
  left_join(node_positions, by = c("value" = "node")) |>
  select(x, y, everything()) 

attributes(karate_layout) <- layout_attributes
```
```{r}
karate_layout
```

```{r}
?geom_node_label
```

```{r}
beziers <- data.frame(
    x = c(1, 2, 3, 4, 4, 6, 6),
    y = c(0, 2, 0, 0, 2, 2, 0),
    type =  'cubic'
)
```

```{r}
ggraph(karate_layout) +
  geom_edge_link() +
  geom_mark_hull(
    aes(
      x,y,
      fill = community_name, 
      description = community_name,
      alpha = 0.5
      ),
    show.legend = FALSE,
    concavity = 1
  ) + 
  scale_colour_brewer(name = "Role", palette = "Set2") + 
  geom_node_label(aes(label = value, colour = role)) +
  labs(
    title = "Zachary's Karate Club",
    subtitle = "Communities assigned by Louvain algorithm",
    caption = "Source: https://networkrepository.com"
  ) +
  theme(legend.position = c(0.9, 0.8))+
  guides(color = guide_legend(override.aes = list(size = 3, shape = 15)))
```

```{r}
ggraph(karate_layout) +
  geom_edge_link() +
  geom_node_label(aes(label = value, colour = role))+
  geom_mark_hull(
    aes(
      x,y,
      fill = community_name, 
      label = community_name,
      alpha = 0.5
      ),
    show.legend = FALSE
  )
```

