---
title: "worldmap"
author: "shuna"
date: "4/5/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tmap)
data(World)
```

```{r}
tm_shape(
  World, 
  projection = "+proj=eck4") + 
  tm_polygons()
```

```{r}
japan <- filter(World, name == "Japan") 
tm_shape(japan) +
  tm_polygons()
```
```{r}
tm_shape(World, projection = "+proj=eck4") +
  tm_polygons(col = "income_grp")
```

```{r}
tm_shape(World, projection = "+proj=eck4") +
  tm_polygons(
    col = "life_exp",
    palette = "GnBu",
    breaks = seq(40, 90, 10),
    title = "Life expectancy"
    )
```

```{r}
View(World)
```

```{r}
tw <- tm_shape(World, projection = "+proj=eck4") +
  tm_polygons(col = "life_exp", title = "Years") +
  tm_layout(
    title = "Life Expectancy",
    inner.margins = c(0.01, 0.2, 0.01, 0.01),
    bg.color = "lightblue",
    earth.boundary = TRUE,
    space.color = "white"
    )

tw
```

```{r}
tw + 
  tm_text("iso_a3", size = "AREA")
```

```{r}
tm_shape(World, projection = "+proj=moll") +
  tm_polygons(col = "life_exp", title = "Years") +
  tm_layout(
    title = "Life Expectancy",
    inner.margins = c(0.02, 0.1, 0.02, 0.02),
    bg.color = "lightblue",
    earth.boundary = TRUE,
    space.color = "white"
    ) +
  tm_text("iso_a3", size = "AREA")
```


```{r}
data(rivers)
glimpse(rivers)
```

```{r}
tm_shape(World) +
  tm_polygons() +
  tm_shape(rivers) +
  tm_lines(col = "blue")
```

```{r}
tm_shape(World) +
  tm_lines(col = "blue") +
  tm_shape(rivers) +
  tm_polygons()
```

```{r}
data(NLD_prov)
glimpse(NLD_prov)
```

```{r}
tm_shape(NLD_prov) +
  tm_polygons(col = c("origin_west", "origin_non_west"))
```

