---
title: "SurvivalAnalysis"
output: html_document
date: '2022-03-28'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

###Load libraries

```{r setup1}
rm(list=ls())
library(survival)
library(survminer)
library(tidyverse)
library(xtable)
```

###Load and process the ovarian dataset from 'survival' package
```{r setup2}
data(ovarian) |>
  print()
glimpse(ovarian)
help(ovarian)
ovarian$rx <- factor(ovarian$rx, 
                     levels = c("1", "2"), 
                     labels = c("A", "B"))
ovarian$resid.ds <- factor(ovarian$resid.ds, 
                           levels = c("1", "2"), 
                           labels = c("no", "yes"))
ovarian$ecog.ps <- factor(ovarian$ecog.ps, 
                          levels = c("1", "2"), 
                          labels = c("good", "bad"))
hist(ovarian$age)
ovarian <- ovarian %>% mutate(age_group = ifelse(age >=50, "old", "young"))
ovarian$age_group <- factor(ovarian$age_group)
```

```{r}
head(ovarian)
```


###Run the survival analysis age vs Rx

```{r survival}
surv_object <- Surv(time = ovarian$futime, event = ovarian$fustat)
surv_object 
```

```{r}
fit<-survfit(surv_object ~ 1, data = ovarian)
summary(fit)

ggsurvplot(fit, data = ovarian,conf.int=FALSE)
ggsurvplot(fit, data = ovarian)
```

```{r}
fit1 <- survfit(surv_object ~ rx, data = ovarian)
summary(fit1)

ggsurvplot(fit1, data = ovarian, pval = TRUE)
ggsurvplot(fit1, data = ovarian, pval = TRUE, conf.int=TRUE)

```

```{r}

fit2 <- survfit(surv_object ~ resid.ds, data = ovarian)
summary(fit2)

ggsurvplot(fit2, data = ovarian, pval = TRUE)
ggsurvplot(fit2, data = ovarian, pval = TRUE, conf.int=TRUE)
```

```{r}
summary(survfit(Surv(futime, fustat) ~ 1, data = ovarian), times = 365.25)
```







