---
title: "Lecture16"
output: html_document
date: '2022-03-31'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(survival)
library(survminer)
library(dplyr)
library(xtable)
```

```{r}
time = c(2, 3, 6, 6, 7, 10, 13, 15, 16, 27, 30, 32)
status = c(1,0,1,1,1,0,1,1,1,1,1,1)
```



###Load and process the ovarian dataset from 'survival' package
```{r setup2}
data(ovarian)
glimpse(ovarian)
help(ovarian)
ovarian$rx <- factor(ovarian$rx, 
                     levels = c("1", "2"), 
                     labels = c("A", "B"))
ovarian$resid.ds <- factor(ovarian$resid.ds, 
                           levels = c("1", "2"), 
                           labels = c("no", "yes"))
ovarian$ecog.ps <- factor(ovarian$ecog.ps, 
                          levels = c("1", "2"), 
                          labels = c("good", "bad"))
hist(ovarian$age)
ovarian <- ovarian %>% mutate(age_group = ifelse(age >=50, "old", "young"))
ovarian$age_group <- factor(ovarian$age_group)
```


###Run the survival analysis age vs Rx

```{r survival}
surv_object <- Surv(time = ovarian$futime, event = ovarian$fustat)
surv_object 


fit1 <- survfit(surv_object ~ rx, data = ovarian)
summary(fit1)
```


```{r}
sd <- survdiff(Surv(futime, fustat) ~ resid.ds, data = ovarian)
sd
```

```{r}
# p-value
1 - pchisq(sd$chisq, length(sd$n) - 1)

ggsurvplot(fit1, data = ovarian, pval = TRUE)

```
```{r}
View(ovarian)
```


```{r}
# which drug? residual disease? age? quality of life? 
fit.coxph <- coxph(surv_object ~ rx + resid.ds + age_group + ecog.ps, data = ovarian)

fit.coxph
cox.zph(fit.coxph)

ggforest(fit.coxph, data = ovarian)


```

```{r}
data(lung)
```

```{r}
lung <- lung |>
  mutate(status = status + 1) |>
  print()
```

```{r}
survival <- Surv(time = lung$time, event = lung$status)
survival
```

```{r}
fit2 <- survfit(survival ~ sex, data = lung)

```

```{r}
fit.coxph_2 <- coxph(survival ~ sex + age + ph.ecog+ ph.karno + meal.cal+ pat.karno + wt.loss,  data =lung)
ggforest(fit.coxph_2, data = lung)
```

```{r}
sessionInfo()
```